# Generated by Django 4.0.4 on 2022-05-26 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuitem_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.restaurant'),
            preserve_default=False,
        ),
    ]
